server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example

spring.http.client.factory=jdk

spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.springframework.web.reactive.function.client.WebClient=DEBUG

vaadin.copilot.enable=false